---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-python-fib-deployment
  labels:
    app: cf-python-fib

spec:
  replicas: 1
  selector:
    matchLabels:
      app: cf-python-fib
  template:
    metadata:
      labels:
        app: cf-python-fib
    spec:
      containers:
      - name: cf-python-fib-server
        image: shagupta/cf-python-app:latest
        tty: true
        imagePullPolicy: Always
        command: ["python3"]
        args: ["rpc_server.py"]
        env:
        - name: RABBITMQ.USERNAME
          valueFrom:
            configMapKeyRef:
              name: rabbit-env
              key: username
        - name: RABBITMQ.USERNAME
          valueFrom:
            configMapKeyRef:
              name: rabbit-env
              key: password
        - name: RABBITMQ.SERVER
          valueFrom:
            configMapKeyRef:
              name: rabbit-env
              key: server
        - name: RABBITMQ.PORT
          valueFrom:
            configMapKeyRef:
              name: rabbit-env
              key: port
        - name: RABBITMQ.VHOST
          valueFrom:
            configMapKeyRef:
              name: rabbit-env
              key: vhost
        - name: PROFILE
          valueFrom:
            configMapKeyRef:
              name: rabbit-env
              key: profile


